<?php

return [
    'generator' => env('CAMPAIGN_GENERATOR', 'mock'),
    'queue' => env('CAMPAIGN_QUEUE', 'campaigns'),
    'processing_mode' => env('CAMPAIGN_PROCESSING_MODE', 'queue'),
    'cron_secret' => env('CRON_SECRET'),
    'monthly_credits' => (int) env('CAMPAIGN_MONTHLY_CREDITS', 50),
    'brand_limit' => (int) env('CAMPAIGN_BRAND_LIMIT', 10),
    'seat_limit' => (int) env('CAMPAIGN_SEAT_LIMIT', 5),
    'cogs_target' => (float) env('CAMPAIGN_COGS_TARGET', 0.25),
    'cogs_alert' => (float) env('CAMPAIGN_COGS_ALERT', 0.50),
    'concierge_emails' => array_values(array_filter(array_map(
        'trim',
        explode(',', env('CAMPAIGN_CONCIERGE_EMAILS', '')),
    ))),
    'source' => [
        'timeout_seconds' => 20,
        'max_redirects' => 3,
        'max_bytes' => 2_000_000,
        'max_image_bytes' => 15_000_000,
        'max_image_candidates' => 12,
        'max_extracted_characters' => 60_000,
    ],
    'media' => [
        'uploads_enabled' => env('CAMPAIGN_MEDIA_UPLOADS_ENABLED', true),
        'disk' => env('CAMPAIGN_MEDIA_DISK', 'local'),
        'ffmpeg' => env('FFMPEG_PATH', '/opt/homebrew/bin/ffmpeg'),
        'ffprobe' => env('FFPROBE_PATH', '/opt/homebrew/bin/ffprobe'),
        'max_video_seconds' => 90,
        'min_frames' => 8,
        'max_frames' => 16,
        'scene_threshold' => 0.18,
        'dedupe_hamming_distance' => 8,
        'transcription_model' => env('OPENAI_TRANSCRIPTION_MODEL', 'gpt-4o-mini-transcribe'),
    ],
    'banners' => [
        'enabled' => env('BANNER_STUDIO_ENABLED', true),
        'generator' => env('BANNER_GENERATOR', 'mock'),
        'model' => env('GOOGLE_BANNER_MODEL', 'gemini-3.1-flash-image'),
        'included_count' => 3,
        'additional_credit_cost' => 1,
        'aspect_ratio' => '4:5',
        'image_size' => '1K',
        'width' => 1080,
        'height' => 1350,
        'retry_attempts' => 3,
        'max_input_images' => 1,
        'disk' => env('BANNER_STORAGE_DISK', env('CAMPAIGN_MEDIA_DISK', 'local')),
        'prices_per_million' => [
            'input' => 0.50,
            'output_text' => 3.00,
            'output_image' => 60.00,
        ],
    ],
    'openai' => [
        'base_url' => env('OPENAI_BASE_URL', 'https://api.openai.com/v1'),
        'model' => env('OPENAI_CAMPAIGN_MODEL', 'gpt-5.4-mini'),
        'fallback_models' => array_values(array_filter(array_map('trim', explode(',', env('OPENAI_CAMPAIGN_FALLBACK_MODELS', ''))))),
        'reasoning_effort' => env('OPENAI_REASONING_EFFORT', 'low'),
        'timeout_seconds' => (int) env('OPENAI_TIMEOUT_SECONDS', 120),
        'retry_attempts' => (int) env('OPENAI_RETRY_ATTEMPTS', 3),
        'retry_backoff_ms' => [250, 1000],
        'prices_per_million' => [
            'gpt-5.4-mini' => ['input' => 0.75, 'cached_input' => 0.075, 'output' => 4.50],
            'openai/gpt-5.4-mini' => ['input' => 0.75, 'cached_input' => 0.075, 'output' => 4.50],
        ],
    ],
    'google' => [
        'project' => env('GOOGLE_CLOUD_PROJECT'),
        'project_number' => env('GOOGLE_CLOUD_PROJECT_NUMBER'),
        'location' => env('GOOGLE_CLOUD_LOCATION', 'global'),
        'model' => env('GOOGLE_GEMINI_MODEL', 'gemini-3.5-flash'),
        'service_account_email' => env('GOOGLE_SERVICE_ACCOUNT_EMAIL'),
        'vercel_audience' => env('GCP_AUDIENCE'),
        'vercel_token_exchange_url' => env('VERCEL_OIDC_TOKEN_EXCHANGE_URL', 'https://oidc.vercel.com/~token'),
        'base_url' => env('GOOGLE_VERTEX_BASE_URL', 'https://aiplatform.googleapis.com/v1'),
        'sts_audience' => env('GOOGLE_STS_AUDIENCE'),
        'sts_token_url' => env('GOOGLE_STS_TOKEN_URL', 'https://sts.googleapis.com/v1/token'),
        'service_account_impersonation_url' => env('GOOGLE_SERVICE_ACCOUNT_IMPERSONATION_URL'),
        'timeout_seconds' => (int) env('GOOGLE_VERTEX_TIMEOUT_SECONDS', 120),
        'retry_attempts' => (int) env('GOOGLE_VERTEX_RETRY_ATTEMPTS', 3),
        'retry_backoff_ms' => [250, 1000],
        'prices_per_million' => [
            'gemini-3.5-flash' => ['input' => 2.70, 'cached_input' => 0.27, 'output' => 16.20],
        ],
    ],
];
